os: linux
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-27.0.3
    - android-27
before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "build-tools;27.0.3"
  - nvm install node
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
install:
  - npm ci
scripts:
  - "./android/gradlew assembleRelease -p android/"
